name: Push_Pull Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (or the version required)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies
        run: mvn clean install -DskipTests
 
      - name: Run test suites
        run: mvn clean verify -Dcucumber.filter.tags=@HCSAPI -Denvironment=qa
 
      - name: Run Serenity BDD Tests
        run: mvn verify -Pdefault
        continue-on-error: true  # Ensures workflow continues even if tests fail

      - name: Upload Serenity Report
        if: always()  # Ensures report is uploaded even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity
